trigger:
 - main

pool:
   name: 'selfhosted'

steps:
 - script: |
     sudo apt-get update -y
     sudo apt install -y ansible
     ansible --version
   displayName: 'ansible installed'

 - script: |
     sudo apt-get update -y
     sudo apt-get install -y ansible-lint
     ansible-lint --version
   displayName: 'Ansible Lint Installed'

 - script: ansible-lint
   displayName: "run ansible lint"

 - task: DownloadSecureFile@1
   name: pemfile
   inputs:
     secureFile: 'ansi_key.pem'
   displayName: "downloading pem file"
 - script: |
       sudo ln -s $(pemfile.secureFilePath) ~/.ssh
       ls -al
   displayName: "saving .pem file"

 - script: |
       cd ~/.ssh
       sudo chmod 0600 ~/.ssh/ansi_key.pem
       ls -al
   displayName: "changing key's  permmisions"

 - script: |
       ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u ubuntu -i ./host_inventory ./playbooks/apache-install.yml --private-key '~/.ssh/ansi_key.pem'
       ls -al
   displayName: "Installing Apache"

 - script: |
         ANSIBLE_HOST_KEY_CHECKING=False ANSIBLE_ROLES_PATH=./roles
         ansible-playbook -u ubuntu -i ./host_inventory ./playbooks/website-update.yml --private-key '~/.ssh/ansi_key.pem'
   displayName: "running website update playbook"

 - script: |
         ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_ROLES_PATH=./roles
         ansible-playbook -u ubuntu -i ./host_inventory ./playbooks/website-test.yml --private-key '~/.ssh/ansi_key.pem'
   displayName: "running website test playbook"
