trigger:
 - main

pool:
   name: 'selfhosted'

steps:
 - script: |
     sudo apt-get update -y
     sudo apt install -y ansible
     ansible --version
   displayName: 'ansible installed'

 - script: |
     sudo apt-get update -y
     sudo apt-get install -y ansible-lint
     ansible-lint --version
   displayName: 'Ansible Lint Installed'

 - script: ansible-lint
   displayName: "run ansible lint"

 - script: |
         ANSIBLE_HOST_KEY_CHECKING=false
         ansible-playbook -u ubuntu -i ~/ansible-basics/host_inventory
         ./playbooks/apache.install.yml --private-key ~/ansible-basics          

