trigger:
 - main

pool:
   name: 'selfhosted'

steps:
 - script: |
     sudo apt-get update -y
     sudo apt install -y ansible
     ansible --version
   displayName: 'ansible installed'

 - script: |
     sudo apt-get update -y
     sudo apt-get install -y ansible-lint
     ansible-lint --version
   displayName: 'Ansible Lint Installed'

 - script: ansible-lint
   displayName: "run ansible lint"

 - script: |
       sudo chmod 400 ./home/ubuntu/.ssh/ansible_key.pem
       ls -al

 - script: |
       ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u ubuntu -i ./host_inventory ./playbooks/apache-install.yml --private-key '/home/ubuntu/.ssh/ansible_key.pem'
       ls -al
   displayName: "Installing Apache"
 - script: ANSIBLE_HOST_KEY_CHECKING=False ANSIBLE_ROLES_PATH=./roles && ansible-playbook -u ubuntu -i ./host_inventory ./playbooks/website-update.yml --private-key '/home/ubuntu/.ssh/ansible_key.pem'
