- name: set index.html
  set_fact:
    file_path: /vars/www/html
- name: copy var.html file
  copy:
     src: vars.html
     dest: " {{ file_path }}/vars.html"
     owner: root
     group: root
     mode: 0755
- name: redirect from index.html to vars.html
  lineinfile: 
     path: "{{ file_path }}/index.html"
     line: <a href=vars.html>variable page</a>
     insertafter: EOF
  ignore_errors: "{{ ansible_check_mode }}"
- name: insert hostname from ansible facts
  lineinfile:
    path: "{{ file_path }}/vars.html"
    line: <p> my name is {{ ansible-hostname }}</p>
    ignore_errors: "{{ ansible_check_mode }}"
  l

