---
- name: install & configure apache
  hosts: webservers
  become: yes
  become_user: root

  tasks:
  - name: install apache
    apt:
      name: apache2
      state: latest
      update_cache: yes
  - name: enable & start service
    service:
      name: apache2
      enabled: yes
      state: started
  - name: remove existing index.html
    file:
      path: /var/www/html/index.html
      state: absent
  - name: creating empty index.html
    file:
      path: /var/www/html/index.html
      state: touch
      owner: root
      group: root
      mode: 0755
  - name: adding content in index.html file
    lineinfile:
      path: /var/www/html/index.html
      line: Namaste Ansible!!


