---
- name: test website
  hosts: webservers
  become: yes
  become_user: root

  tasks:
  - name: check port 80 on manage node
    wait_for:
      port: 80
      state: started
      timeout: 3

  - name: verify apache is available
    uri:
      url: http://{{ ansible_host }}/index.html
    delegate_to: localhost

  - name: stat apache2
    stat:
      path: /usr/sbin/apache2
    register: i

  - name: fail is apache2 doesnt exists
    assert:
      that:
        - "i.stat.exists"
      fail_msg: "/usr/sbin/apache2 does not exist!"
      success_msg: "/usr/sbin/apache2 exists"

  - name: verify apache2 enabled
    shell: systemctl list-unit-files | grep apache2.service | awk -F\  '{print $2}'
    register: c

  - name: fail if apache2 not enabled
    assert:
      that:
        - "c.stdout == 'enabled'"
      fail_msg: "apache2 not enabled"
      success_msg: "apache2 is enabled"

  - name: stat index.html
    stat:
      path: /var/www/html/index.html
    register: a

  - name: index exists
    assert:
      that:
        - "a.stat.exists"
        - "a.stat.pw_name == 'root'"
      fail_msg: "index.html not exist"
      success_msg: "index.html exists"

  - name: stat vars.html
    stat:
      path: /var/www/html/vars.html
    register: v

  - name: vars exists
    assert:
      that:
        - "v.stat.exists"
        - "v.stat.pw_name == 'root'"
      fail_msg: "vars.html not exist"
      success_msg: "vars.html exists"
